import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import {ClerkProvider} from '@clerk/nextjs'
import { ThemeProvider } from '@/components/theme-provider'
import { cn } from '@/lib/utils'
const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Discord Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <ThemeProvider
        attribute='class'
        defaultTheme='dark'
        enableSystem={false}
        storageKey='discord-theme'
        >
        <body className={cn(font.className,"bg-white dark:bg-[#313338]")}>{children}</body>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  )
}
